<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');?>
<div id="chart" class="chart"></div>
<map name="map1" id="map1">
    <area href="javascript:void(0)" alt="" title="<b>1961</b> Apertura del primer taller de reparaciones  electromecánicas en calle Godoy Cruz y Sargento Cabral  de San Martín."  shape="circle" coords="60,298,5" />
    <area href="javascript:void(0)" alt="" title="<b>1964</b> Traslado a instalaciones más amplias  en la calle Alem 363 de ese departamento. Empiezan a cimentar la empresa, adquiriendo un terreno sobre la misma avenida."  shape="circle" coords="116,287,5" />
    <area href="javascript:void(0)" alt="" title="<b>1968</b> Construcción del primer galpón, frente a la terminal de Ómnibus. Se comienzan a fabricar, de forma prácticamente artesanal, los  primeros tableros eléctricos."  shape="circle" coords="175,262,5" />
    <area href="javascript:void(0)" alt="" title="<b>1973</b> La empresa se afianza. Se monta el primer taller metalúrgico en Alem 573."  shape="circle" coords="230,234,5" />
    <area href="javascript:void(0)" alt="" title="<b>1976- 1978</b> Se construye el depósito, las oficinas y el salón de atención al público. Se amplían los galpones. Se inicia la actividad de Industria Metalúrgicas y Plegado (<b><u>INPLE</u></b>), sociedad que dura hasta 1985 y que es absorbida aposteriori por EBHSA."  shape="circle" coords="287,215,5" />
    <area href="javascript:void(0)" alt="" title="<b>1983</b> Puesta en marcha de la planta de galvanizado, anexo indispensable para completar el circuito de fabricación de tableros."  shape="circle" coords="344,176,5" />
    <area href="javascript:void(0)" alt="" title="<b>1989</b> Construcción de la planta de pintura termo- convertible, destinada a mejorar la  calidad de terminación de tableros y gabinetes."  shape="circle" coords="400,140,5" />
    <area href="javascript:void(0)" alt="" title="<b>1996</b> Fiel a sus principios, la compañía invierte tiempo y capacidad creativa en estudiar la problemática de los sistemas de bombeo de agua. En ese contexto, establece vínculos comerciales con la multinacional danesa Grundfos."  shape="circle" coords="457,98,5" />
    <area href="javascript:void(0)" alt="" title="<b>1998</b> Grundfos le otorga a EBHSA la habilitación como primera subfactory de electrobombas sumergibles en Sudamérica.<br /> Permaneció como única subfactory en Latinoamérica por más de una década."  shape="circle" coords="514,86,5" />
    <area href="http://www.bottinosa.com/empresa/nuestra-organizacion" alt="" title="<b>1999</b> Inauguración sobre la ruta 7 en el departamento de  San Martín del edificio propio de Subfactory Grundfos." shape="circle" coords="571,82,5" />
    <area href="javascript:void(0)" alt="" title="<b>2000</b> EBHSA certifica normas de calidad ISO 9001."  shape="circle" coords="629,75,5" />
    <area href="javascript:void(0)" alt="" title="<b>2001</b> En plena etapa de crecimiento, la firma cumple 40 años de actividad."  shape="circle" coords="685,70,5" />
    <area href="javascript:void(0)" alt="" title="<b>2004</b> Incorpora a su cartera de productos las mangueras planas Angus, de origen inglés.  Se trata de una marca de prestigio internacional que posiciona a  Bottino en el segmento de  las tuberías flexibles,  que ofrecen  soluciones innovadoras para todas las aplicaciones de transferencia de fluidos."  shape="circle" coords="740,53,5" />
    <area href="javascript:void(0)" alt="" title="<b>2005</b> Anexa la representación de las bombas neumáticas de marca americana Wilden, utilizadas en todo tipo de industrias para el movimiento de fluidos."  shape="circle" coords="798,46,5" />
    <area href="javascript:void(0)" alt="" title="<b>2006</b> Se inicia la construcción de la nueva planta de EBHSA colindante al predio donde, desde 1999, funciona la BH Subfactory Grundfos."  shape="circle" coords="855,40,5" />
    <area href="javascript:void(0)" alt="" title="<b>2007</b> Inauguración de la nueva y actual infraestructura, ubicada sobre el corredor bioceánico, en San Martín, Mendoza.<br />Lanzamiento del generador eólico, que marca la presencia de la empresa en el siglo XXI. <b>“Hoy el desarrollo de tecnología para aprovechar las energías alternativas es uno de nuestros grandes desafíos. Nos interesa estar a la vanguardia: está en la “sangre” de nuestra organización“, Jorge Bottino, presidente de EBHSA.</b>"  shape="circle" coords="909,35,5" />
</map>
